# coding: utf-8

自定义:

  alphabet: qazwsxedcrfvtgb12345yhnujmik,ol.p;/67890'=`[- \]

  algebra:
  
    #
    ##
    # 预处理
      #
      # 声明空格所用的按键和其易于表达的变换编码
      # 增加空格还需在前面的字母表（允许接受并击的按键列表）中期添加
      
    - xform| |一_| # 左手空格
    - xform|-|二_| # 左手次空格
#    - xform|`|三_| # 左手三空格
#    - xform|\[|四_| # 左手四空格
    - xform|\[|一_|


    - xform|'|_一| # 右手空格
    - xform|=|_二| # 右手次空格
#    - xform|\\|_三| # 右手三空格
#    - xform|\]|_四| # 右手四空格
    - xform|\]|_一|

#    - xform|`|中| # 中间的空格
#    - xform|\\|中| # 中间的空格

    # 处理多键映射至同一的空格编码的重复编码
    - xform/(中)+/中/
    
    #
    
    - xform/(二_)?|(_二)?/$2$1/
    #上面这部分可以放在外部配置，读取了再插入chord_composer
    
    
    
    
    # 预处理区
    
    # 符号和数字映射为大写字母，分离其转义干扰
    - xlit|;,./|ACXZ|
    
    # 将编码包装（用一对尖括号包裹起来）
      # 左手编码包装
    - xform/([qwertasdfgzxcvb12345]+)/<$1>/
      # 右手编码包装
    - xform/([yuiophjklAnmCXZ67890]+)/<$1>/
    
    # 包装空格区编码
      # 包裹成： <"左左_><"_右右><"左左_右右> <"中><"左左中><"中右右><"左左中右右> 的形式，从这些形式变换来： 一_二__二_一 、 一_二_中 、 中_二_一 、 一_ 二_中_二_一 、 _二_一 、 一_二_ 、 中
    - xform/([_中一二三四五]+)/<"$1>/
      # 处理只存在左或右的情况
    - xform/<"(.*)_>/<"$1::>/
    - xform/<"_(.*)>/<"::$1>/
      # 处理左(中)右都存在的情况
    - xform/_((中)?)_/:$1:/
    - xform/_//
    - xform/::/_/
    - xform/:(.*):/$1/
    
      # 无空格的时候补一个<"无>标签
    - xform/^(.*)$/$1<"无>/
    - xform/<"(.*)><"无>/<"$1>/
    
    # 处理单手击的表示（添加下划线，表示另一手未击）  #允许存在单手配左中右空格，允许单手数字区表示
    - xform/^<([qwertasdfgzxcvb12345]+)><"(.*)>$/<$1>_<"$2>/
    - xform/^<([yuiophjklAnmCXZ67890]+)><"(.*)>$/_<$1><"$2>/
    
    
    ##########################################
    ##
    # 主处理区（顺序可以随便排）
    
      # 大写字母部分指法映射(齐列)
#    - xform=(<qv>|<mp>|<qg>|<hp>|<sef>|<jil>)=Q=  # 可以写成这样
#    - xform_<qv>|<mp>_Q_
#    - xform=(<qv>|<mp>)=Q=
#    - xform=(<qg>|<hp>)=Q=
    - xform=(<sef>|<jil>)=Q=
#    - xform=(<awf>|<joA>)=Q=
    - xform=(<wv>|<mo>)=W=
#    - xform=(<ev>|<mi>)=E=
#    - xform=(<eg>|<hi>)=E=
#    - xform=(<wef>|<jio>)=E=
#    - xform=(<ser>|<uil>)=E=
    - xform=(<xdf>|<jkX>)=E=
    - xform=(<et>|<yi>)=R=
#    - xform=(<qt>|<yp>)=T=
#    - xform=(<wer>|<uio>)=T=
#    - xform=(<awe>|<ioA>)=T=
    - xform=(<awf>|<joA>)=T=
#    - xform=(<awg>|<hoA>)=T=
    - xform=(<wg>|<ho>)=Y=
#    - xform=(<wt>|<yo>)=U=
#    - xform=(<ser>|<uil>)=U=
#    - xform=(<weg>|<hio>)=U=
#    - xform=(<wer>|<uio>)=U=
    - xform=(<wef>|<jio>)=U=
    - xform=(<eg>|<hi>)=I=
#    - xform=(<wef>|<jio>)=I=
#    - xform=(<qw>|<op>)=I=
#    - xform=(<ae>|<iA>)=I=
#    - xform=(<awe>|<ioA>)=I=
    - xform=(<aw>|<oA>)=O=
    - xform=(<qf>|<jp>)=P=
      #
    - xform=(<av>|<mA>)=A=
    - xform=(<sv>|<ml>)=S=
    - xform=(<dv>|<mk>)=D=
    - xform=(<sg>|<hl>)=F=
    - xform=(<dg>|<hk>)=G=
    - xform=(<ar>|<uA>)=H=
#    - xform=(<xf>|<jX>)=J=
#    - xform=(<db>|<nk>)=J=
#    - xform=(<wef>|<jio>)=J=
    - xform=(<wdf>|<jko>)=J=
    - xform=(<dr>|<uk>)=K=
    - xform=(<wf>|<jo>)=L=
    - xform=(<as>|<lA>)=:=
      #
#    - xform=(<zf>|<jZ>)=Z=
    - xform=(<sdf>|<jkl>)=Z=
    - xform=(<xd>|<kX>)=X=
#    - xform=(<xf>|<jX>)=X=
#    - xform=(<sef>|<jil>)=X=
#    - xform=(<zf>|<jZ>)=X=
    - xform=(<cf>|<jC>)=C=
#    - xform=(<xdf>|<jkX>)=C=
#    - xform=(<ac>|<CA>)=C=
#    - xform=(<cg>|<hC>)=C=
#    - xform=(<zs>|<lZ>)=V=
    - xform=(<sdv>|<mkl>)=V=
#    - xform=(<qw>|<op>)=B=
#    - xform=(<ab>|<nA>)=B=
#    - xform=(<xdf>|<jkX>)=B=
#    - xform=(<xdv>|<mkX>)=B=
    - xform=(<asv>|<mlA>)=B=
    - xform=(<wd>|<ko>)=N=
    - xform=(<se>|<il>)=M=
    - xform=(<at>|<yA>)=<=
    - xform=(<ag>|<hA>)=>=
    - xform=(<zx>|<XZ>)=?=
    
      # 小写字母部分指法映射(齐列)
    - xform=(<q>|<p>)=q=
    - xform=(<w>|<o>)=w=
    - xform=(<e>|<i>)=e=
    - xform=(<r>|<u>)=r=
    - xform=(<t>|<y>)=t=
    - xform=(<ef>|<ji>)=y=
    - xform=(<er>|<ui>)=u=
    - xform=(<we>|<io>)=i=
    - xform=(<wr>|<uo>)=o=
    - xform=(<qr>|<up>)=p=
      #
    - xform=(<a>|<A>)=a=
    - xform=(<s>|<l>)=s=
    - xform=(<d>|<k>)=d=
    - xform=(<f>|<j>)=f=
    - xform=(<g>|<h>)=g=
    - xform=(<sr>|<ul>)=h=
    - xform=(<df>|<jk>)=j=
    - xform=(<sd>|<kl>)=k=
    - xform=(<sf>|<jl>)=l=
    - xform=(<af>|<jA>)=;=
      #
    - xform=(<z>|<Z>)=z=
    - xform=(<rg>|<hu>)=z=
    - xform=(<x>|<X>)=x=
    - xform=(<c>|<C>)=c=
    - xform=(<v>|<m>)=v=
    - xform=(<b>|<n>)=b=
    - xform=(<sc>|<Cl>)=n=
    - xform=(<cv>|<mC>)=m=
    - xform=(<xc>|<CX>)=,=
    - xform=(<xv>|<mX>)=.=
    - xform=(<zv>|<mZ>)=/=
    
      # 数字部分指法映射
    - xform=(<1>)=1=
    - xform=(<2>)=2=
    - xform=(<3>)=3=
    - xform=(<4>)=4=
    - xform=(<5>)=5=
    - xform=(<35>)=6=
    - xform=(<34>)=7=
    - xform=(<23>)=8=
    - xform=(<24>)=9=
    - xform=(<14>)=0=
    - xform=(<12>)=!=
      #
    - xform=(<6>)=6=
    - xform=(<7>)=7=
    - xform=(<8>)=8=
    - xform=(<9>)=9=
    - xform=(<0>)=0=
    - xform=(<68>)="=
    - xform=(<78>)=%=
    - xform=(<89>)=~=
    - xform=(<79>)=@=
    - xform=(<70>)=*=
    - xform=(<90>)=&=
    
    
    - xform=(<wer>)=8=
    - xform=(<sdf>)=7=
    - xform=(<xcv>)=9=
    - xform=(<asdf>)=0=
    
    - xform=(<uio>)=~=
    - xform=(<jkl>)=`=
    - xform=(<mCX>)=!=
    - xform=(<jkl;>)=@=


    # 主映射区结束
    
    ####
    ##
    
    
    ########################################

    
    - xform/^UU<"无>$/ /
    - xform/^;;<"无>$/ /
    - xform/^1i$/<"1>/
    - xform/^2i$/<"2>/
    - xform/^3i$/<"3>/
    - xform/^4i$/<"4>/

    
    #
    
      # 空格组合区
    
    - xform|<"中>|$1<"1>|
    
    - xform=(.+)_<"无>=$1_<"0>=
    - xform=_(.+)<"无>=_$1<"0>=
    - xform=(.+)<"无>=$1<"0>=
    - xform=^<"无>==
    
    - xform|(.+)_<"一_>|$1_<"1>|
    - xform|_(.+)<"一_>|_$1<"1>|
    - xform|(.+)<"一_>|$1<"1>|
    - xform|^<"一_>|<"2>|
    
    - xform|(.+)_<"_一>|$1_<"1>|
    - xform|_(.+)<"_一>|_$1<"1>|
    - xform|(.+)<"_一>|$1<"1>|
    - xform|^<"_一>| |
    
    - xform|(.+)_<"二_>|$1_<"0>。|
    - xform|_(.+)<"二_>|_$1<"0>。|
    - xform|(.+)<"二_>|$1<"0>。|
    - xform|^<"二_>|<"4>|
    
    - xform|(.+)_<"_二>|$1_<"0>，|
    - xform|_(.+)<"_二>|_$1<"0>，|
    - xform|(.+)<"_二>|$1<"0>，|
    - xform|^<"_二>|<"3>|
    
    - xform|(.+)_<"一_一>|$1_<"0>；|
    - xform|_(.+)<"一_一>|_$1<"0>；|
    - xform|(.+)<"一_一>|$1<"0>；|
    - xform|^<"一_一>|<"2>|
    
    - xform|(.+)<"二_二>|$1<"0>、|
    - xform|^<"二_二>|<"5>|
    
    - xform|(.+)_<"一二_>|$1_<"1>|
#    - xform|(.+)_<"一_二>|$1_<"1>，|
    - xform|_(.+)<"_二一>|_$1<"1>|
#    - xform|_(.+)<"二_一>|_$1<"1>。|
    - xform|(.+)<"一二_>|$1<"1>|
    - xform|(.+)<"_二一>|$1<"1>|
    
    ##########
    #主处理区可以写在chord_composer里让用户自行处理
    
    
    #
#    - xform=^.*(<"?[0-9]>)$=$1|$2|=
    
    
      # 屏蔽未定义的指法
    - xform/<无>//
    - xform=(__)<".+>==
#    - xform/.*<.+>.*(<".+>)/$1/
    - xform/.*<.+>.*(<".+>)//
    #不要用erase消除，应该不能用在chord_composer中
    
    
    # 处理双边数字上屏
    - xform/^([0-9])([0-9])$/$1__$2/
    


  output_format:
    #输出后处理
    
    
    # 使用竖线作为分界符
    - xform=<"(.+)>(.*)$=|$1$2|=
    - xlit/无一二三四五中/012345C/
    - xlit|；，。、|;,./|

#  comment:
  prompt_format:
    # 并击合成过程中指法提示
    
    - xform=<"(.*)>=:$1=
    - xform=^ $=_=
    - xlit|一二|壹贰|
#    - xlit/无壹贰三四五中/⓪①②③④⑤©/
    
